name: Test

on:
  push

jobs:
  test:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Coding style
        run: |
          pycodestyle . --exclude=.venv --max-line-length=120
      - name: Doctest
        run: |
          python -m doctest -f -v README.md callback_decorator.py
      - name: Unit test
        run: |
          python -m unittest -v
